language: node_js
node_js:
  - "stable"
install:
  - npm install
before_script:
  - psql -c 'create database ride_my_way;' -U postgres
script:
  - npm test
services:
  - postgresql
cache:
  directories:
    - "node_modules"
after_success: npm run coverage
